trigger: none
pool:
  name: 'WEB-1'

parameters:
- name: CREATE_PR
  displayName: "Create PR ?"
  type: string
  default: 'NO'
  values:
    - YES
    - NO
- name: SHOULD_RELEASE
  type: string
  default: 'false'
  values:
    - 'true'
    - 'false'
- name: BRANCH
  type: string
  default: 'dev'
  displayName: "Select Branch"
  values:
    - 'dev'
    - 'devops'
    - 'alpha'
    - 'beta'

# Define pipeline IDs as variables
variables:
  BACKEND_PIPELINE_ID: 111
  FRONTEND_PIPELINE_ID: 109

jobs:
- job: Trigger_Backend
  displayName: '🚀 Trigger Backend Pipeline'
  steps:
  - checkout: none
  - template: azure-pipelines/templates/trigger-pipeline.yml
    parameters:
      PIPELINE_ID: $(BACKEND_PIPELINE_ID)
      BRANCH: ${{ parameters.BRANCH }}
      CREATE_PR: ${{ parameters.CREATE_PR }}
      SHOULD_RELEASE: ${{ parameters.SHOULD_RELEASE }}
      side: "backend"

- job: Trigger_Frontend
  displayName: '🎨 Trigger Frontend Pipeline'
  dependsOn: []  # Run in parallel
  steps:
  - checkout: none
  - template: azure-pipelines/templates/trigger-pipeline.yml
    parameters:
      PIPELINE_ID: $(FRONTEND_PIPELINE_ID)
      BRANCH: ${{ parameters.BRANCH }}
      CREATE_PR: ${{ parameters.CREATE_PR }}
      SHOULD_RELEASE: ${{ parameters.SHOULD_RELEASE }}
      side: "frontend"